### ISSUE TITLE
JamfAADActivator.sh

### ISSUE THREAD

**Issue by sean-enright** [benwhitis/Jamf_Conditional_Access#3]
Just curious what this script is and how it can be utilized, I looked around on your wiki and cannot see any reference to it. TIA

**Comment by benwhitis** [comment]
Hey @sean-enright 

This script can re-activate computers that fall into one of these scenarios: https://github.com/benwhitis/Jamf_Conditional_Access/wiki/Jamf-Conditional-Access-Prompts-and-Troubleshooting-Deactivation

It's less invasive for end users than a full re-registration.
